In [1]:
!pip install pandas

Collecting pandas
  Downloading pandas-1.0.3-cp37-cp37m-win_amd64.whl (8.7 MB)
Requirement already satisfied: numpy>=1.13.3 in c:\conda\lib\site-packages (from pandas) (1.18.4)
Requirement already satisfied: python-dateutil>=2.6.1 in c:\conda\lib\site-packages (from pandas) (2.8.1)
Collecting pytz>=2017.2
  Downloading pytz-2020.1-py2.py3-none-any.whl (510 kB)
Requirement already satisfied: six>=1.5 in c:\conda\lib\site-packages (from python-dateutil>=2.6.1->pandas) (1.14.0)
Installing collected packages: pytz, pandas
Successfully installed pandas-1.0.3 pytz-2020.1

In [3]:
import pandas as pd
df = pd.read_csv("iris.csv")
df

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [5]:
a = df["sepal.length"]
print(a)

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ...
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal.length, Length: 150, dtype: float64

In [9]:
a = df.iloc[:20]
a

    sepal.length  sepal.width  petal.length  petal.width variety
0            5.1          3.5           1.4          0.2  Setosa
1            4.9          3.0           1.4          0.2  Setosa
2            4.7          3.2           1.3          0.2  Setosa
3            4.6          3.1           1.5          0.2  Setosa
4            5.0          3.6           1.4          0.2  Setosa
5            5.4          3.9           1.7          0.4  Setosa
6            4.6          3.4           1.4          0.3  Setosa
7            5.0          3.4           1.5          0.2  Setosa
8            4.4          2.9           1.4          0.2  Setosa
9            4.9          3.1           1.5          0.1  Setosa
10           5.4          3.7           1.5          0.2  Setosa
11           4.8          3.4           1.6          0.2  Setosa
12           4.8          3.0           1.4          0.1  Setosa
13           4.3          3.0           1.1          0.1  Setosa
14           5.8          4.0           1.2          0.2  Setosa
15           5.7          4.4           1.5          0.4  Setosa
16           5.4          3.9           1.3          0.4  Setosa
17           5.1          3.5           1.4          0.3  Setosa
18           5.7          3.8           1.7          0.3  Setosa
19           5.1          3.8           1.5          0.3  Setosa

In [6]:
a = df[df["variety"]=="Setosa"]
a

    sepal.length  sepal.width  petal.length  petal.width variety
0            5.1          3.5           1.4          0.2  Setosa
1            4.9          3.0           1.4          0.2  Setosa
2            4.7          3.2           1.3          0.2  Setosa
3            4.6          3.1           1.5          0.2  Setosa
4            5.0          3.6           1.4          0.2  Setosa
5            5.4          3.9           1.7          0.4  Setosa
6            4.6          3.4           1.4          0.3  Setosa
7            5.0          3.4           1.5          0.2  Setosa
8            4.4          2.9           1.4          0.2  Setosa
9            4.9          3.1           1.5          0.1  Setosa
10           5.4          3.7           1.5          0.2  Setosa
11           4.8          3.4           1.6          0.2  Setosa
12           4.8          3.0           1.4          0.1  Setosa
13           4.3          3.0           1.1          0.1  Setosa
14           5.8          4.0           1.2          0.2  Setosa
15           5.7          4.4           1.5          0.4  Setosa
16           5.4          3.9           1.3          0.4  Setosa
17           5.1          3.5           1.4          0.3  Setosa
18           5.7          3.8           1.7          0.3  Setosa
19           5.1          3.8           1.5          0.3  Setosa
20           5.4          3.4           1.7          0.2  Setosa
21           5.1          3.7           1.5          0.4  Setosa
22           4.6          3.6           1.0          0.2  Setosa
23           5.1          3.3           1.7          0.5  Setosa
24           4.8          3.4           1.9          0.2  Setosa
25           5.0          3.0           1.6          0.2  Setosa
26           5.0          3.4           1.6          0.4  Setosa
27           5.2          3.5           1.5          0.2  Setosa
28           5.2          3.4           1.4          0.2  Setosa
29           4.7          3.2           1.6          0.2  Setosa
30           4.8          3.1           1.6          0.2  Setosa
31           5.4          3.4           1.5          0.4  Setosa
32           5.2          4.1           1.5          0.1  Setosa
33           5.5          4.2           1.4          0.2  Setosa
34           4.9          3.1           1.5          0.2  Setosa
35           5.0          3.2           1.2          0.2  Setosa
36           5.5          3.5           1.3          0.2  Setosa
37           4.9          3.6           1.4          0.1  Setosa
38           4.4          3.0           1.3          0.2  Setosa
39           5.1          3.4           1.5          0.2  Setosa
40           5.0          3.5           1.3          0.3  Setosa
41           4.5          2.3           1.3          0.3  Setosa
42           4.4          3.2           1.3          0.2  Setosa
43           5.0          3.5           1.6          0.6  Setosa
44           5.1          3.8           1.9          0.4  Setosa
45           4.8          3.0           1.4          0.3  Setosa
46           5.1          3.8           1.6          0.2  Setosa
47           4.6          3.2           1.4          0.2  Setosa
48           5.3          3.7           1.5          0.2  Setosa
49           5.0          3.3           1.4          0.2  Setosa